name: Master CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master    
  workflow_dispatch:    

jobs:
  test-get-kernel-sources-action:
    runs-on: acuated-arm64-4cpu-12gb
    steps:
      - uses: actions/checkout@v4
      
      - uses: self-actuated/get-kernel-sources@master
          
      - name: Check that a dummy kmod can be built
        run: make
